{"name": "test_case_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "test\\case\\test_case_01.py:17: in test_case_03\n    assert False\nE   assert False"}, "description": "测试函数03", "attachments": [{"name": "log", "source": "b9932fc2-c037-44f3-a46e-d1da0e2ca96c-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "45e7ed9f-a5a2-499e-9e7b-7e471721e24d-attachment.txt", "type": "text/plain"}], "start": 1744526030424, "stop": 1744526030424, "uuid": "6f212fa3-0ff6-4bf0-86de-2319f4188941", "historyId": "b15cd841e953350658c54c10b35fb853", "testCaseId": "b15cd841e953350658c54c10b35fb853", "fullName": "test.case.test_case_01#test_case_03", "labels": [{"name": "parentSuite", "value": "test.case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "AlansPc"}, {"name": "thread", "value": "20620-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.case.test_case_01"}]}