{"name": "test_case_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "test\\case\\test_case_01.py:17: in test_case_03\n    assert False\nE   assert False"}, "description": "测试函数03", "attachments": [{"name": "log", "source": "470a8771-cf4f-4436-85a6-2e39a122b413-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "be56850d-b62f-489f-80fe-ab97e2170af0-attachment.txt", "type": "text/plain"}], "start": 1744526205261, "stop": 1744526205262, "uuid": "75803afd-ae33-4d35-92f1-b2c6e954c908", "historyId": "b15cd841e953350658c54c10b35fb853", "testCaseId": "b15cd841e953350658c54c10b35fb853", "fullName": "test.case.test_case_01#test_case_03", "labels": [{"name": "parentSuite", "value": "test.case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "AlansPc"}, {"name": "thread", "value": "25268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.case.test_case_01"}]}