{"name": "test_case_03", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "test\\case\\test_case_01.py:17: in test_case_03\n    assert False\nE   assert False"}, "description": "测试函数03", "attachments": [{"name": "log", "source": "f2a960a9-ff13-427d-b9f4-f0a8bc407b6d-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "3dabe723-be17-4aa8-8a46-3e3ca95d130f-attachment.txt", "type": "text/plain"}], "start": 1744527907419, "stop": 1744527907419, "uuid": "5a811be4-4dca-495e-bed1-e376da530898", "historyId": "b15cd841e953350658c54c10b35fb853", "testCaseId": "b15cd841e953350658c54c10b35fb853", "fullName": "test.case.test_case_01#test_case_03", "labels": [{"name": "parentSuite", "value": "test.case"}, {"name": "suite", "value": "test_case_01"}, {"name": "host", "value": "AlansPc"}, {"name": "thread", "value": "26124-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.case.test_case_01"}]}